// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7u8fUViuh5hpHEyFHuT265ms2IRPPWSo',
    appId: '1:540061197287:web:8ad8865ce0175529881342',
    messagingSenderId: '540061197287',
    projectId: 'flashcardquizapp-80fcc',
    authDomain: 'flashcardquizapp-80fcc.firebaseapp.com',
    storageBucket: 'flashcardquizapp-80fcc.firebasestorage.app',
    measurementId: 'G-JD14YBVJNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAziCjEDJkKGlGZwlrnzMKsSVZPzW040Cc',
    appId: '1:540061197287:android:50e42c27e7d773bd881342',
    messagingSenderId: '540061197287',
    projectId: 'flashcardquizapp-80fcc',
    storageBucket: 'flashcardquizapp-80fcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxmTPJNjtmIKP0smD9pFQhBpd1xveXA4',
    appId: '1:540061197287:ios:ce7d6d9b0104c6e5881342',
    messagingSenderId: '540061197287',
    projectId: 'flashcardquizapp-80fcc',
    storageBucket: 'flashcardquizapp-80fcc.firebasestorage.app',
    iosBundleId: 'com.example.flashcardQuizApp',
  );
}
